'use strict';

/**
 * app.js — Application entry point
 *
 * Initialises all services, wires DOM events, and manages app lifecycle.
 * Credentials are injected via window.__AI_NAV_CONFIG (set by Vercel env).
 *
 * Security: no credentials in source — see governance/security-policy.md A02.
 */

import APIService from './api.js';
import { createStore } from './state.js';
import UIService from './ui.js';
import StorageService from './storage.js';
import ValidationService from './validation.js';

// ── Config injected at runtime by Vercel environment ─────────────────────────
// In production, a small inline <script> (generated by vercel.json rewrites)
// sets window.__AI_NAV_CONFIG = { supabaseUrl: "...", supabaseAnonKey: "..." }.
// Falls back to localStorage cache for offline resilience.
const _envConfig = (typeof window !== 'undefined' && window.__AI_NAV_CONFIG) || {};

// ── App State ─────────────────────────────────────────────────────────────────
const store = createStore({
  auth: { user: null, tenantId: null, isLoggedIn: false },
  filterConfig: {
    keywords: [],
    weights: { github: 50, arxiv: 30, hn: 20 },
    threshold: 60,
  },
  clearDimensions: { cost: 20, latency: 20, efficiency: 20, assurance: 20, reliability: 20 },
  analyses: [],
  ui: { currentView: 'dashboard', sidebarOpen: false },
});

// ── Helpers ───────────────────────────────────────────────────────────────────

function showView(viewId) {
  document.querySelectorAll('[data-view]').forEach(el => {
    el.hidden = true;
    el.setAttribute('aria-hidden', 'true');
  });
  const target = document.getElementById(`view-${viewId}`);
  if (target) {
    target.hidden = false;
    target.removeAttribute('aria-hidden');
  }

  document.querySelectorAll('[data-view]').forEach(link => {
    const isActive = link.dataset.view === viewId;
    link.classList.toggle('sidebar-nav__link--active', isActive);
    if (isActive) link.setAttribute('aria-current', 'page');
    else link.removeAttribute('aria-current');
  });

  const titleEl = document.getElementById('page-title');
  const titles = {
    dashboard: 'Dashboard',
    'domain-filter': 'Domain-Filter-Konfiguration',
    'clear-analysis': 'CLEAR-Analyse',
    'signal-feed': 'Signal-Feed',
    history: 'Analyse-History',
    'audit-trail': 'Audit-Trail',
    usage: 'Nutzung & Kosten',
  };
  if (titleEl) titleEl.textContent = titles[viewId] || viewId;

  store.set('ui', { ...store.get('ui'), currentView: viewId });
}

function showAuth() {
  document.getElementById('auth-screen').hidden = false;
  document.getElementById('app-dashboard').hidden = true;
}

function showDashboard(user) {
  document.getElementById('auth-screen').hidden = true;
  document.getElementById('app-dashboard').hidden = false;
  document.getElementById('user-name').textContent = user.email || '—';
  document.getElementById('user-avatar').textContent = (user.email || '?')[0].toUpperCase();
  document.getElementById('user-tenant').textContent = user.tenantId || 'Tenant';
  showView('dashboard');
}

function setLoading(on) {
  document.getElementById('loading-overlay').hidden = !on;
}

function notify(message, type = 'info') {
  UIService.showNotification(message, type);
}

// ── Auth ──────────────────────────────────────────────────────────────────────

async function handleLogin(email, password) {
  setLoading(true);
  const result = await APIService.login(email, password);
  setLoading(false);

  if (!result.ok) {
    document.getElementById('auth-errors').hidden = false;
    document.getElementById('auth-errors').textContent = result.error || 'Anmeldung fehlgeschlagen.';
    return;
  }

  const { user } = result.data;
  store.set('auth', { user, tenantId: user.tenantId, isLoggedIn: true });
  StorageService.set(user.tenantId, 'last_user', user.email);
  document.getElementById('auth-errors').hidden = true;
  showDashboard(user);
  loadFilterConfig(user.tenantId);
}

async function handleLogout() {
  await APIService.logout();
  store.set('auth', { user: null, tenantId: null, isLoggedIn: false });
  showAuth();
}

// ── Filter Config ─────────────────────────────────────────────────────────────

function renderKeywords(keywords) {
  const container = document.getElementById('keywords-list');
  container.innerHTML = '';
  if (!keywords.length) {
    container.innerHTML = '<span style="color: var(--color-text-muted); font-size: 0.875rem;">Noch keine Keywords. Fügen Sie Ihr erstes Keyword hinzu.</span>';
    return;
  }
  keywords.forEach(kw => {
    const chip = document.createElement('span');
    chip.setAttribute('role', 'listitem');
    chip.style.cssText = 'display:inline-flex;align-items:center;gap:0.375rem;background:var(--color-primary-light,#e8f4fd);color:var(--color-primary,#1a73e8);padding:0.25rem 0.75rem;border-radius:999px;font-size:0.875rem;';
    chip.textContent = kw;

    const removeBtn = document.createElement('button');
    removeBtn.type = 'button';
    removeBtn.setAttribute('aria-label', `Keyword "${kw}" entfernen`);
    removeBtn.style.cssText = 'background:none;border:none;cursor:pointer;padding:0;line-height:1;font-size:1rem;color:inherit;opacity:0.7;';
    removeBtn.textContent = '×';
    removeBtn.addEventListener('click', () => removeKeyword(kw));

    chip.appendChild(removeBtn);
    container.appendChild(chip);
  });
}

async function addKeyword() {
  const input = document.getElementById('keyword-input');
  const errorEl = document.getElementById('keyword-error');
  const value = input.value.trim();

  errorEl.hidden = true;

  const validation = ValidationService.validateKeyword(value);
  if (!validation.valid) {
    errorEl.textContent = validation.error;
    errorEl.hidden = false;
    return;
  }

  const current = store.get('filterConfig').keywords;
  if (current.includes(value)) {
    errorEl.textContent = 'Dieses Keyword ist bereits aktiv.';
    errorEl.hidden = false;
    return;
  }

  const updated = [...current, value];
  store.set('filterConfig', { ...store.get('filterConfig'), keywords: updated });
  renderKeywords(updated);
  input.value = '';
}

async function removeKeyword(kw) {
  const current = store.get('filterConfig').keywords;
  const updated = current.filter(k => k !== kw);
  store.set('filterConfig', { ...store.get('filterConfig'), keywords: updated });
  renderKeywords(updated);
}

async function loadFilterConfig(tenantId) {
  const cached = StorageService.get(tenantId, 'filter_config');
  if (cached) {
    store.set('filterConfig', cached);
    applyFilterConfigToUI(cached);
  }

  const result = await APIService.getFilterConfig(tenantId);
  if (result.ok && result.data) {
    store.set('filterConfig', result.data);
    StorageService.set(tenantId, 'filter_config', result.data);
    applyFilterConfigToUI(result.data);
  }
}

function applyFilterConfigToUI(config) {
  renderKeywords(config.keywords || []);

  const weights = config.weights || {};
  [['github', 50], ['arxiv', 30], ['hn', 20]].forEach(([src, def]) => {
    const v = weights[src] ?? def;
    const slider = document.getElementById(`weight-${src}`);
    const output = document.getElementById(`weight-${src}-output`);
    if (slider) { slider.value = v; slider.setAttribute('aria-valuenow', v); }
    if (output) output.textContent = v;
  });

  const threshold = config.threshold ?? 60;
  const thSlider = document.getElementById('relevance-threshold');
  const thDisplay = document.getElementById('threshold-display');
  if (thSlider) { thSlider.value = threshold; thSlider.setAttribute('aria-valuenow', threshold); }
  if (thDisplay) thDisplay.textContent = threshold;
}

async function saveFilterConfig() {
  const { tenantId } = store.get('auth');
  if (!tenantId) return;

  const weights = {
    github: parseInt(document.getElementById('weight-github').value, 10),
    arxiv: parseInt(document.getElementById('weight-arxiv').value, 10),
    hn: parseInt(document.getElementById('weight-hn').value, 10),
  };

  const weightsError = document.getElementById('weights-error');
  if (Object.values(weights).every(v => v === 0)) {
    weightsError.hidden = false;
    return;
  }
  weightsError.hidden = true;

  const config = {
    ...store.get('filterConfig'),
    weights,
    threshold: parseInt(document.getElementById('relevance-threshold').value, 10),
  };

  setLoading(true);
  const result = await APIService.saveFilterConfig(tenantId, config);
  setLoading(false);

  if (result.ok) {
    store.set('filterConfig', config);
    StorageService.set(tenantId, 'filter_config', config);
    notify('Filtereinstellungen gespeichert.', 'success');
  } else {
    notify('Änderung konnte nicht gespeichert werden. Bitte versuchen Sie es erneut.', 'error');
  }
}

// ── CLEAR Analysis ────────────────────────────────────────────────────────────

function updateClearTotal() {
  const dims = ['cost', 'latency', 'efficiency', 'assurance', 'reliability'];
  const total = dims.reduce((sum, d) => sum + parseInt(document.getElementById(`dim-${d}`).value, 10), 0);
  const display = document.getElementById('clear-total-display');
  const error = document.getElementById('clear-total-error');
  const current = document.getElementById('clear-total-current');
  const btn = document.getElementById('btn-run-analysis');

  display.textContent = `${total}%`;
  display.style.color = total === 100 ? 'var(--color-success, #1a7f4b)' : 'var(--color-error, #c0392b)';
  error.hidden = total === 100;
  if (current) current.textContent = total;
  btn.disabled = total !== 100;
}

async function runClearAnalysis() {
  const { tenantId } = store.get('auth');
  if (!tenantId) return;

  const dims = ['cost', 'latency', 'efficiency', 'assurance', 'reliability'];
  const total = dims.reduce((sum, d) => sum + parseInt(document.getElementById(`dim-${d}`).value, 10), 0);
  if (total !== 100) {
    notify('Die Summe der CLEAR-Dimensionen muss genau 100% ergeben.', 'error');
    return;
  }

  const dimensions = Object.fromEntries(
    dims.map(d => [d, parseInt(document.getElementById(`dim-${d}`).value, 10)])
  );
  const context = document.getElementById('clear-context').value.trim();

  setLoading(true);
  const result = await APIService.runClearAnalysis(tenantId, { dimensions, context });
  setLoading(false);

  if (!result.ok) {
    notify('Analyse fehlgeschlagen: ' + (result.error || 'Unbekannter Fehler'), 'error');
    return;
  }

  const resultEl = document.getElementById('analysis-result');
  const contentEl = document.getElementById('analysis-result-content');
  resultEl.hidden = false;

  // Render result as formatted text (XSS-safe via textContent)
  contentEl.innerHTML = '';
  const pre = document.createElement('pre');
  pre.style.cssText = 'white-space: pre-wrap; word-break: break-word; font-family: inherit;';
  pre.textContent = result.data.recommendation || JSON.stringify(result.data, null, 2);
  contentEl.appendChild(pre);

  // Add to history
  const analyses = [result.data, ...store.get('analyses')].slice(0, 50);
  store.set('analyses', analyses);
  renderAnalysisHistory(analyses);

  notify('CLEAR-Analyse abgeschlossen.', 'success');
}

function renderAnalysisHistory(analyses) {
  const container = document.getElementById('analysis-history');
  if (!analyses.length) return;
  container.innerHTML = '';
  analyses.forEach((a, i) => {
    const item = document.createElement('div');
    item.style.cssText = 'padding: var(--space-md) 0; border-bottom: 1px solid var(--color-border);';
    item.setAttribute('role', 'article');
    item.setAttribute('aria-label', `Analyse ${i + 1}`);
    const date = a.created_at ? new Date(a.created_at).toLocaleString('de-DE') : '—';
    const p = document.createElement('p');
    p.style.cssText = 'font-size: 0.875rem; color: var(--color-text-muted); margin: 0;';
    p.textContent = date;
    const rec = document.createElement('p');
    rec.style.cssText = 'margin: var(--space-xs) 0 0;';
    rec.textContent = (a.recommendation || '').substring(0, 120) + '…';
    item.appendChild(p);
    item.appendChild(rec);
    container.appendChild(item);
  });
}

// ── Navigation ────────────────────────────────────────────────────────────────

function initNavigation() {
  document.addEventListener('click', e => {
    const link = e.target.closest('[data-view], [data-navigate]');
    if (!link) return;
    const view = link.dataset.view || link.dataset.navigate;
    if (!view) return;
    e.preventDefault();
    showView(view);

    // Close sidebar on mobile
    if (store.get('ui').sidebarOpen) toggleSidebar(false);
  });
}

function toggleSidebar(force) {
  const sidebar = document.getElementById('app-sidebar');
  const overlay = document.getElementById('sidebar-overlay');
  const toggle = document.getElementById('mobile-menu-toggle');
  const isOpen = force !== undefined ? force : !store.get('ui').sidebarOpen;
  sidebar.classList.toggle('app-sidebar--open', isOpen);
  overlay.classList.toggle('sidebar-overlay--visible', isOpen);
  toggle.setAttribute('aria-expanded', String(isOpen));
  store.set('ui', { ...store.get('ui'), sidebarOpen: isOpen });
}

// ── Range slider live feedback ────────────────────────────────────────────────

function initSliders() {
  // Source weight sliders
  ['github', 'arxiv', 'hn'].forEach(src => {
    const slider = document.getElementById(`weight-${src}`);
    const output = document.getElementById(`weight-${src}-output`);
    if (!slider) return;
    slider.addEventListener('input', () => {
      output.textContent = slider.value;
      slider.setAttribute('aria-valuenow', slider.value);
    });
  });

  // Threshold slider
  const thSlider = document.getElementById('relevance-threshold');
  if (thSlider) {
    thSlider.addEventListener('input', () => {
      const display = document.getElementById('threshold-display');
      if (display) display.textContent = thSlider.value;
      thSlider.setAttribute('aria-valuenow', thSlider.value);
    });
  }

  // CLEAR dimension sliders
  ['cost', 'latency', 'efficiency', 'assurance', 'reliability'].forEach(d => {
    const slider = document.getElementById(`dim-${d}`);
    const output = document.getElementById(`dim-${d}-output`);
    if (!slider) return;
    slider.addEventListener('input', () => {
      output.textContent = slider.value;
      slider.setAttribute('aria-valuenow', slider.value);
      updateClearTotal();
    });
  });
}

// ── Boot ──────────────────────────────────────────────────────────────────────

async function boot() {
  // Credentials check
  if (!_envConfig.supabaseUrl || !_envConfig.supabaseAnonKey) {
    // Development mode: show auth with warning
    console.warn('[app] No Supabase config — running in offline/demo mode');
    document.getElementById('auth-screen').hidden = false;
    document.getElementById('auth-screen').querySelector('.auth-card__subtitle').textContent =
      'Demo-Modus — Backend nicht konfiguriert';
  } else {
    APIService.init({
      supabaseUrl: _envConfig.supabaseUrl,
      supabaseAnonKey: _envConfig.supabaseAnonKey,
      getAccessToken: () => store.get('auth').user?.accessToken ?? null,
    });
  }

  initNavigation();
  initSliders();

  // Auth form
  document.getElementById('login-form')?.addEventListener('submit', e => {
    e.preventDefault();
    const email = document.getElementById('login-email').value;
    const password = document.getElementById('login-password').value;
    handleLogin(email, password);
  });

  // User menu → logout
  document.getElementById('user-menu-btn')?.addEventListener('click', () => {
    if (confirm('Abmelden?')) handleLogout();
  });

  // Mobile menu
  document.getElementById('mobile-menu-toggle')?.addEventListener('click', () => toggleSidebar());
  document.getElementById('sidebar-overlay')?.addEventListener('click', () => toggleSidebar(false));

  // Filter actions
  document.getElementById('btn-add-keyword')?.addEventListener('click', addKeyword);
  document.getElementById('keyword-input')?.addEventListener('keydown', e => {
    if (e.key === 'Enter') { e.preventDefault(); addKeyword(); }
  });
  document.getElementById('btn-save-filter')?.addEventListener('click', saveFilterConfig);
  document.getElementById('btn-reset-filter')?.addEventListener('click', () => {
    const { tenantId } = store.get('auth');
    if (tenantId) loadFilterConfig(tenantId);
  });

  // CLEAR actions
  document.getElementById('btn-run-analysis')?.addEventListener('click', runClearAnalysis);
  updateClearTotal();

  // PDF export
  document.getElementById('btn-export-pdf')?.addEventListener('click', () => window.print());

  // Check existing session
  const session = await APIService.getSession?.();
  if (session?.user) {
    store.set('auth', { user: session.user, tenantId: session.user.tenantId, isLoggedIn: true });
    showDashboard(session.user);
    loadFilterConfig(session.user.tenantId);
  } else {
    showAuth();
  }
}

document.addEventListener('DOMContentLoaded', boot);
